[theme]
base = "dark"
primaryColor = "#615fff"
backgroundColor = "#0f172b"
secondaryBackgroundColor = "#1d293d"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
